// This file was generated by tauri-specta. Do not edit this file manually.

/** tauri-specta plugin bindings */
export type PluginCommands = {
  "unlock_app": (password: string) => Promise<boolean>;
  "lock_app": () => Promise<void>;
  "get_encryption_status": () => Promise<boolean>;
  "change_password": (old_password: string, new_password: string) => Promise<void>;
};

/** tauri-specta plugin name */
export const PLUGIN_NAME = "encryption";

/** tauri-specta command names */
export const COMMAND_NAMES = {
  "unlock_app": "plugin:encryption|unlock_app",
  "lock_app": "plugin:encryption|lock_app",
  "get_encryption_status": "plugin:encryption|get_encryption_status",
  "change_password": "plugin:encryption|change_password",
};

/** tauri-specta commands */
export const commands = {
  "unlock_app": async (password: string): Promise<boolean> => {
    return await (window as any).__TAURI_INVOKE__(COMMAND_NAMES["unlock_app"], { password });
  },
  "lock_app": async (): Promise<void> => {
    return await (window as any).__TAURI_INVOKE__(COMMAND_NAMES["lock_app"]);
  },
  "get_encryption_status": async (): Promise<boolean> => {
    return await (window as any).__TAURI_INVOKE__(COMMAND_NAMES["get_encryption_status"]);
  },
  "change_password": async (old_password: string, new_password: string): Promise<void> => {
    return await (window as any).__TAURI_INVOKE__(COMMAND_NAMES["change_password"], { old_password, new_password });
  },
};
